baseURL: https://gircore.github.io/
title: Gir.Core
theme: book

languageCode: en-us
uglyURLs: true

contentDir: ../content
publishDir: ../output
themesDir: ../themes

menu:
  # before: []
  after:
    - name: "Documentation"
      url: "https://gircore.github.io/api/index.html"
      weight: 9
    - name: "Github"
      url: "https://github.com/gircore/gir.core"
      weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  BookTheme: "auto"
  BookLogo: "logo.png"