name: Deploy website

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit hash to load the gir.core source code from
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout website
      uses: actions/checkout@v3
      with:
        path: 'website'

    - name: Checkout gir.core docs
      uses: actions/checkout@v3
      with:
        repository: 'gircore/gir.core'
        ref: 'main'
        path: 'gircore-docs'
    
    - name: Checkout gir.core
      uses: actions/checkout@v3
      with:
        repository: 'gircore/gir.core'
        ref: ${{ github.event.inputs.commit}}
        path: 'gircore'
        submodules: 'true'
      
    - name: Move readme into website
      run: cp ./gircore-docs/docs/readme.md ./website/docfx/

    - name: Rename readme
      run: mv ./website/docfx/readme.md ./website/docfx/index.md
      
    - name: Move docs into website
      run: cp -r ./gircore-docs/docs/docs ./website/docfx/docs

    - name: Move images into website
      run: cp -r ./gircore-docs/docs/img/* ./website/docfx/img

    - name: Prepare .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Call generator
      run: dotnet fsi GenerateLibs.fsx
      working-directory: './gircore/src'

    - name: Restore solution
      run: dotnet restore GirCore.Libs.slnf
      working-directory: './gircore/src'

    - name: Install docfx
      run: dotnet tool update -g docfx

    - name: Build docs into website
      run: docfx website/docfx/docfx.json
  
    - name: Publish website
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: main
        publish_dir: ./website/output
        #cname: gircore.tiede.org
