name: Deploy website

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout website
      uses: actions/checkout@v3
      with:
        path: 'website'

    - name: Checkout gir.core
      uses: actions/checkout@v3
      with:
        repository: 'gircore/gir.core'
        ref: 'main'
        path: 'gircore'
        submodules: 'true'

    - name: Create content folder
      run: mkdir ./website/content/
      
    - name: Move readme into website
      run: cp ./gircore/docs/readme.md ./website/content/

    - name: Rename readme
      run: mv ./website/content/readme.md ./website/content/_index.md
      
    - name: Move docs into website
      run: cp -r ./gircore/docs/docs ./website/content/docs

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build website
      run: hugo --minify
      working-directory: './website/hugo'

    - name: Prepare .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Call generator
      run: dotnet fsi GenerateLibs.fsx
      working-directory: './gircore/src'

    - name: Restore solution
      run: dotnet restore GirCore.Libs.slnf
      working-directory: './gircore/src'

    - name: Install docfx
      run: dotnet install -g docfx

    - name: Build docs into website
      run: docfx docfx/docfx.json
  
    - name: Publish website
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: main
        publish_dir: ./website/output
        #cname: gircore.tiede.org
