name: Deploy website

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout website
      uses: actions/checkout@v3
      with:
        path: 'website'

    - name: Checkout gir.core
      uses: actions/checkout@v3
      with:
        repository: 'gircore/gir.core'
        ref: 'main'
        path: 'gircore'
        submodules: 'true'
        
    #- name: Prepare .NET
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: '6.0.102'
        
    #- name: Call generator
    #  run: dotnet fsi GenerateLibs.fsx
    #  working-directory: './gircore/src'

    #- name: Move api docs into website
    #  run: cp -r ./gircore/Docs/Api ./website/content/api
      
    - name: Move readme into website
      run: cp ./gircore/docs/readme.md ./website/content/

    - name: Rename readme
      run: mv ./website/content/readme.md ./website/content/_index.md
      
    - name: Move docs into website
      run: cp -r ./gircore/docs/docs ./website/content/docs

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build website
      run: hugo --minify
      working-directory: './website/hugo'
  
    - name: Publish website
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: main
        publish_dir: ./website/output
        #cname: gircore.tiede.org
